export const categoriesData = [
  {
    name: "Men's Clothing",
    slug: 'mens-clothing',
    parentCategory: null,
    image: 'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?w=600&auto=format&fit=crop&q=80',
    description: 'Contemporary menswear tailoring, casuals, and luxury essentials',
    sortOrder: 1,
  },
  {
    name: 'Watches',
    slug: 'watches',
    parentCategory: null,
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&auto=format&fit=crop&q=80',
    description: 'Precision luxury chronographs, minimalists, and everyday timepieces',
    sortOrder: 2,
  },
  {
    name: 'Footwear',
    slug: 'footwear',
    parentCategory: null,
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&auto=format&fit=crop&q=80',
    description: 'Premium handcrafted leather shoes, loafers, and designer sneakers',
    sortOrder: 3,
  },
  {
    name: 'Accessories',
    slug: 'accessories',
    parentCategory: null,
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&auto=format&fit=crop&q=80',
    description: 'Curated Italian leather wallets, full-grain belts, and designer eyewear',
    sortOrder: 4,
  },
  // Subcategories under Men's Clothing
  {
    name: 'T-Shirts',
    slug: 't-shirts',
    parentSlug: 'mens-clothing',
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&auto=format&fit=crop&q=80',
    description: 'Pima and Supima cotton crew necks, oversized tees, and polos',
    sortOrder: 1,
  },
  {
    name: 'Shirts',
    slug: 'shirts',
    parentSlug: 'mens-clothing',
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&auto=format&fit=crop&q=80',
    description: 'Crisp oxford button-downs, linen casual shirts, and dress shirts',
    sortOrder: 2,
  },
  {
    name: 'Jeans',
    slug: 'jeans',
    parentSlug: 'mens-clothing',
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&auto=format&fit=crop&q=80',
    description: 'Selvedge, slim tapered, and relaxed straight-leg denim',
    sortOrder: 3,
  },
  {
    name: 'Trousers',
    slug: 'trousers',
    parentSlug: 'mens-clothing',
    image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&auto=format&fit=crop&q=80',
    description: 'Tailored pleated trousers, modern chinos, and linen pants',
    sortOrder: 4,
  },
  // Subcategories under Watches
  {
    name: 'Analog Watches',
    slug: 'analog-watches',
    parentSlug: 'watches',
    image: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=600&auto=format&fit=crop&q=80',
    description: 'Classic three-hand dress watches with sapphire crystal',
    sortOrder: 1,
  },
  {
    name: 'Chronograph Watches',
    slug: 'chronograph-watches',
    parentSlug: 'watches',
    image: 'https://images.unsplash.com/photo-1533139502658-0198f920d8e8?w=600&auto=format&fit=crop&q=80',
    description: 'Multi-dial motorsport and aviation inspired timing instruments',
    sortOrder: 2,
  },
  // Subcategories under Footwear
  {
    name: 'Sneakers',
    slug: 'sneakers',
    parentSlug: 'footwear',
    image: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=600&auto=format&fit=crop&q=80',
    description: 'Minimalist low-top leather trainers and retro lifestyle runners',
    sortOrder: 1,
  },
  {
    name: 'Formal Shoes',
    slug: 'formal-shoes',
    parentSlug: 'footwear',
    image: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=600&auto=format&fit=crop&q=80',
    description: 'Goodyear welted Oxfords, Derbies, and Monk straps',
    sortOrder: 2,
  },
  // Subcategories under Accessories
  {
    name: 'Wallets',
    slug: 'wallets',
    parentSlug: 'accessories',
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&auto=format&fit=crop&q=80',
    description: 'Bifold, cardholder, and RFID-blocking full-grain leather wallets',
    sortOrder: 1,
  },
  {
    name: 'Belts',
    slug: 'belts',
    parentSlug: 'accessories',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80',
    description: 'Reversible dress belts and brushed brass buckle casual belts',
    sortOrder: 2,
  },
  {
    name: 'Sunglasses',
    slug: 'sunglasses',
    parentSlug: 'accessories',
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&auto=format&fit=crop&q=80',
    description: 'Polarized acetate aviators, wayfarers, and clubmasters',
    sortOrder: 3,
  },
];
